### ISSUE TITLE
cutting $map['js'] in two distinct attributes

### ISSUE THREAD

**Issue by vincent3569** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#13]
hi
actualy, you designed CodeIgniter-Google-Maps-V3-API-Library to have 2 outputs in the html page, as following

<html>
<head>
<?php echo $map['js']; ?>
</head>
<body>
<?php echo $map['html']; ?>
</body>
</html>

something would be intersesting :
cut $map['js'] in 2 attributes :
- $map['head_js'] to set the scripts to load in the header
- $map['map_js'] to set the needed javascripts to load the map

with that, you can design the html as you wish (ie the javascript not realy needs to be in the header).

**Comment by BIOSTALL** [comment]
Hi vincent3569, 

Sorry for taking so long to get back to you. I'm just wondering why you'd need to put the two separate bits of JS in different places in your view.

You can, at the moment, move <?php echo $map['js']; ?> to be anywhere you like in your view (header, footer, wherever) and the map will still work.

Due to the age of this issue, and because I see no real need for this feature at the moment I'm going to close this issue. Please feel free to re-open it if you do feel there is still a requirement for this, and why.

Thanks :)
