### ISSUE TITLE
my map output not showing street

### ISSUE THREAD

**Issue by navotera** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#5]
i cannot understand why my map output not showing the street  or any info of the name of the street ... and it just showing blank.. it just there's my marker alone...... ?

**Comment by zabad** [comment]
Same here. Have you solved the problem?

**Comment by BIOSTALL** [comment]
Due to the age of this issue, and because there is no example provided whereby this can be replicated, I'm gong to close the issue. 

Should you be able to provide an example I will take a look.

Please remember, the library isn't Google Maps... it simply brings in the map tiles and provides you with a way to interact with the Google Maps API. If the same is happening at http://maps.google.com then I'm afraid it's beyond my control.

Thanks
